[project]
authors = ["vitor"]
entry = "main.sw"
license = "Apache-2.0"
name = "swap_exact_output_script"

[dependencies]
interfaces = { path = "../../libraries/interfaces" }
math = { path = "../../libraries/math" }
utils = { path = "../../libraries/utils" }