/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.98.0
*/

import type {
  Account,
  Address,
  BigNumberish,
  BN,
  FunctionFragment,
  InvokeFunction,
  Provider,
  StorageSlot,
} from 'fuels';
import { Contract, Interface } from 'fuels';

import type { Enum, Vec } from './common';

export enum AccessErrorInput {
  NotOwner = 'NotOwner',
}
export enum AccessErrorOutput {
  NotOwner = 'NotOwner',
}
export type IdentityInput = Enum<{
  Address: AddressInput;
  ContractId: ContractIdInput;
}>;
export type IdentityOutput = Enum<{
  Address: AddressOutput;
  ContractId: ContractIdOutput;
}>;
export enum InitializationErrorInput {
  CannotReinitialized = 'CannotReinitialized',
}
export enum InitializationErrorOutput {
  CannotReinitialized = 'CannotReinitialized',
}
export type StateInput = Enum<{
  Uninitialized: undefined;
  Initialized: IdentityInput;
  Revoked: undefined;
}>;
export type StateOutput = Enum<{
  Uninitialized: void;
  Initialized: IdentityOutput;
  Revoked: void;
}>;

export type AddressInput = { bits: string };
export type AddressOutput = AddressInput;
export type ConfigInput = {
  min_submissions: BigNumberish;
  round_time: BigNumberish;
  deviation_threshold: BigNumberish;
};
export type ConfigOutput = {
  min_submissions: BN;
  round_time: BN;
  deviation_threshold: BN;
};
export type ConfigUpdatedInput = {
  min_submissions: BigNumberish;
  round_time: BigNumberish;
  deviation_threshold: BigNumberish;
};
export type ConfigUpdatedOutput = {
  min_submissions: BN;
  round_time: BN;
  deviation_threshold: BN;
};
export type ContractIdInput = { bits: string };
export type ContractIdOutput = ContractIdInput;
export type OwnershipSetInput = { new_owner: IdentityInput };
export type OwnershipSetOutput = { new_owner: IdentityOutput };
export type OwnershipTransferredInput = {
  new_owner: IdentityInput;
  previous_owner: IdentityInput;
};
export type OwnershipTransferredOutput = {
  new_owner: IdentityOutput;
  previous_owner: IdentityOutput;
};
export type PriceInput = {
  price: BigNumberish;
  timestamp: BigNumberish;
  round_id: BigNumberish;
};
export type PriceOutput = { price: BN; timestamp: BN; round_id: BN };
export type PriceSubmitterUpdateInput = {
  submitter: IdentityInput;
  is_valid: boolean;
};
export type PriceSubmitterUpdateOutput = {
  submitter: IdentityOutput;
  is_valid: boolean;
};
export type RoundInput = {
  round_id: BigNumberish;
  price: BigNumberish;
  round_start: BigNumberish;
  round_end: BigNumberish;
  completed: boolean;
  round_failed: boolean;
};
export type RoundOutput = {
  round_id: BN;
  price: BN;
  round_start: BN;
  round_end: BN;
  completed: boolean;
  round_failed: boolean;
};
export type RoundCompletedInput = {
  round_id: BigNumberish;
  price: BigNumberish;
  submissions_count: BigNumberish;
};
export type RoundCompletedOutput = {
  round_id: BN;
  price: BN;
  submissions_count: BN;
};
export type RoundFailedInput = { round_id: BigNumberish };
export type RoundFailedOutput = { round_id: BN };
export type RoundStartedInput = {
  round_id: BigNumberish;
  round_start: BigNumberish;
  round_end: BigNumberish;
};
export type RoundStartedOutput = {
  round_id: BN;
  round_start: BN;
  round_end: BN;
};

const abi = {
  programType: 'contract',
  specVersion: '1',
  encodingVersion: '1',
  concreteTypes: [
    {
      type: '()',
      concreteTypeId:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
    },
    {
      type: 'bool',
      concreteTypeId:
        'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
    },
    {
      type: 'enum standards::src5::AccessError',
      concreteTypeId:
        '3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d',
      metadataTypeId: 1,
    },
    {
      type: 'enum standards::src5::State',
      concreteTypeId:
        '192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c',
      metadataTypeId: 2,
    },
    {
      type: 'enum std::identity::Identity',
      concreteTypeId:
        'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
      metadataTypeId: 3,
    },
    {
      type: 'enum sway_libs::ownership::errors::InitializationError',
      concreteTypeId:
        '1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893',
      metadataTypeId: 4,
    },
    {
      type: 'str',
      concreteTypeId:
        '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
    },
    {
      type: 'struct events::ConfigUpdated',
      concreteTypeId:
        'c03d2cf5a8ccc25a3bddb9f19daa56503610c857cc816fd4e0dc5c304252a5d3',
      metadataTypeId: 7,
    },
    {
      type: 'struct events::PriceSubmitterUpdate',
      concreteTypeId:
        '32c198ced8ac5e0726f103e71c2cea69689f58aae2e81fc91ebf1bf9441196e2',
      metadataTypeId: 8,
    },
    {
      type: 'struct events::RoundCompleted',
      concreteTypeId:
        '6c7753f567a783bb9490cf39a6c2adf9aeeae5b8d0fd6fab4fa60f44bbc38781',
      metadataTypeId: 9,
    },
    {
      type: 'struct events::RoundFailed',
      concreteTypeId:
        '9db8d353f5813dc990b6e512e34d6346db0d828e4effdb0b135628da94d43cd4',
      metadataTypeId: 10,
    },
    {
      type: 'struct events::RoundStarted',
      concreteTypeId:
        'aa041b4f398d5fe70f8bd393ace65e7f309a532ea3edc2f2adbd07522ceb35ce',
      metadataTypeId: 11,
    },
    {
      type: 'struct interfaces::price_feed::Config',
      concreteTypeId:
        '08c7b1c40fb82180533a24ed6971f6a8f7f498b977dbc1b7ac2966eeae484005',
      metadataTypeId: 12,
    },
    {
      type: 'struct interfaces::price_feed::Price',
      concreteTypeId:
        '3ea06096b46105f14974866a35fb7dabb5bf8d457d080b6df6c9aa1e209e8557',
      metadataTypeId: 13,
    },
    {
      type: 'struct interfaces::price_feed::Round',
      concreteTypeId:
        'eb2edb1dc40bc7580ae912b318e606c1c4b8d059054fe66e51cb7a131cf57dae',
      metadataTypeId: 14,
    },
    {
      type: 'struct std::vec::Vec<enum std::identity::Identity>',
      concreteTypeId:
        '2f79033d0d3729398611309f48578b56cf5162ba85e50f4d8fb79c9d9d1abc7b',
      metadataTypeId: 18,
      typeArguments: [
        'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
      ],
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipSet',
      concreteTypeId:
        'e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5',
      metadataTypeId: 19,
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipTransferred',
      concreteTypeId:
        'b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308',
      metadataTypeId: 20,
    },
    {
      type: 'u64',
      concreteTypeId:
        '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
    },
  ],
  metadataTypes: [
    {
      type: 'b256',
      metadataTypeId: 0,
    },
    {
      type: 'enum standards::src5::AccessError',
      metadataTypeId: 1,
      components: [
        {
          name: 'NotOwner',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum standards::src5::State',
      metadataTypeId: 2,
      components: [
        {
          name: 'Uninitialized',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
        {
          name: 'Initialized',
          typeId: 3,
        },
        {
          name: 'Revoked',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'enum std::identity::Identity',
      metadataTypeId: 3,
      components: [
        {
          name: 'Address',
          typeId: 15,
        },
        {
          name: 'ContractId',
          typeId: 16,
        },
      ],
    },
    {
      type: 'enum sway_libs::ownership::errors::InitializationError',
      metadataTypeId: 4,
      components: [
        {
          name: 'CannotReinitialized',
          typeId:
            '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
        },
      ],
    },
    {
      type: 'generic T',
      metadataTypeId: 5,
    },
    {
      type: 'raw untyped ptr',
      metadataTypeId: 6,
    },
    {
      type: 'struct events::ConfigUpdated',
      metadataTypeId: 7,
      components: [
        {
          name: 'min_submissions',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_time',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'deviation_threshold',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct events::PriceSubmitterUpdate',
      metadataTypeId: 8,
      components: [
        {
          name: 'submitter',
          typeId: 3,
        },
        {
          name: 'is_valid',
          typeId:
            'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
        },
      ],
    },
    {
      type: 'struct events::RoundCompleted',
      metadataTypeId: 9,
      components: [
        {
          name: 'round_id',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'price',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'submissions_count',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct events::RoundFailed',
      metadataTypeId: 10,
      components: [
        {
          name: 'round_id',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct events::RoundStarted',
      metadataTypeId: 11,
      components: [
        {
          name: 'round_id',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_start',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_end',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct interfaces::price_feed::Config',
      metadataTypeId: 12,
      components: [
        {
          name: 'min_submissions',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_time',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'deviation_threshold',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct interfaces::price_feed::Price',
      metadataTypeId: 13,
      components: [
        {
          name: 'price',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'timestamp',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_id',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
    },
    {
      type: 'struct interfaces::price_feed::Round',
      metadataTypeId: 14,
      components: [
        {
          name: 'round_id',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'price',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_start',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_end',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'completed',
          typeId:
            'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
        },
        {
          name: 'round_failed',
          typeId:
            'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
        },
      ],
    },
    {
      type: 'struct std::address::Address',
      metadataTypeId: 15,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::contract_id::ContractId',
      metadataTypeId: 16,
      components: [
        {
          name: 'bits',
          typeId: 0,
        },
      ],
    },
    {
      type: 'struct std::vec::RawVec',
      metadataTypeId: 17,
      components: [
        {
          name: 'ptr',
          typeId: 6,
        },
        {
          name: 'cap',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      typeParameters: [5],
    },
    {
      type: 'struct std::vec::Vec',
      metadataTypeId: 18,
      components: [
        {
          name: 'buf',
          typeId: 17,
          typeArguments: [
            {
              name: '',
              typeId: 5,
            },
          ],
        },
        {
          name: 'len',
          typeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      typeParameters: [5],
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipSet',
      metadataTypeId: 19,
      components: [
        {
          name: 'new_owner',
          typeId: 3,
        },
      ],
    },
    {
      type: 'struct sway_libs::ownership::events::OwnershipTransferred',
      metadataTypeId: 20,
      components: [
        {
          name: 'new_owner',
          typeId: 3,
        },
        {
          name: 'previous_owner',
          typeId: 3,
        },
      ],
    },
  ],
  functions: [
    {
      inputs: [
        {
          name: 'round_id',
          concreteTypeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      name: 'end_round',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [],
      name: 'get_config',
      output:
        '08c7b1c40fb82180533a24ed6971f6a8f7f498b977dbc1b7ac2966eeae484005',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [],
      name: 'get_price',
      output:
        '3ea06096b46105f14974866a35fb7dabb5bf8d457d080b6df6c9aa1e209e8557',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'round_id',
          concreteTypeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      name: 'get_round_data',
      output:
        'eb2edb1dc40bc7580ae912b318e606c1c4b8d059054fe66e51cb7a131cf57dae',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'owner',
          concreteTypeId:
            'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
        {
          name: 'config',
          concreteTypeId:
            '08c7b1c40fb82180533a24ed6971f6a8f7f498b977dbc1b7ac2966eeae484005',
        },
        {
          name: 'submitters',
          concreteTypeId:
            '2f79033d0d3729398611309f48578b56cf5162ba85e50f4d8fb79c9d9d1abc7b',
        },
      ],
      name: 'initialize',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'submitter',
          concreteTypeId:
            'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
      ],
      name: 'is_price_submitter',
      output:
        'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [],
      name: 'latest_round',
      output:
        'eb2edb1dc40bc7580ae912b318e606c1c4b8d059054fe66e51cb7a131cf57dae',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'config',
          concreteTypeId:
            '08c7b1c40fb82180533a24ed6971f6a8f7f498b977dbc1b7ac2966eeae484005',
        },
      ],
      name: 'set_config',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'submitter',
          concreteTypeId:
            'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
        {
          name: 'is_valid',
          concreteTypeId:
            'b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903',
        },
      ],
      name: 'set_price_submitter',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'price',
          concreteTypeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
        {
          name: 'round_id',
          concreteTypeId:
            '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
        },
      ],
      name: 'submit_price',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [],
      name: 'total_active_submitters',
      output:
        '1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
    {
      inputs: [
        {
          name: 'new_owner',
          concreteTypeId:
            'ab7cd04e05be58e3fc15d424c2c4a57f824a2a2d97d67252440a3925ebdc1335',
        },
      ],
      name: 'transfer_ownership',
      output:
        '2e38e77b22c314a449e91fafed92a43826ac6aa403ae6a8acb6cf58239fbaf5d',
      attributes: [
        {
          name: 'storage',
          arguments: ['read', 'write'],
        },
      ],
    },
    {
      inputs: [],
      name: 'owner',
      output:
        '192bc7098e2fe60635a9918afb563e4e5419d386da2bdbf0d716b4bc8549802c',
      attributes: [
        {
          name: 'storage',
          arguments: ['read'],
        },
      ],
    },
  ],
  loggedTypes: [
    {
      logId: '10098701174489624218',
      concreteTypeId:
        '8c25cb3686462e9a86d2883c5688a22fe738b0bbc85f458d2d2b5f3f667c6d5a',
    },
    {
      logId: '11365066017224080841',
      concreteTypeId:
        '9db8d353f5813dc990b6e512e34d6346db0d828e4effdb0b135628da94d43cd4',
    },
    {
      logId: '12250946913436524519',
      concreteTypeId:
        'aa041b4f398d5fe70f8bd393ace65e7f309a532ea3edc2f2adbd07522ceb35ce',
    },
    {
      logId: '2161305517876418151',
      concreteTypeId:
        '1dfe7feadc1d9667a4351761230f948744068a090fe91b1bc6763a90ed5d3893',
    },
    {
      logId: '16280289466020123285',
      concreteTypeId:
        'e1ef35033ea9d2956f17c3292dea4a46ce7d61fdf37bbebe03b7b965073f43b5',
    },
    {
      logId: '3657372386567413255',
      concreteTypeId:
        '32c198ced8ac5e0726f103e71c2cea69689f58aae2e81fc91ebf1bf9441196e2',
    },
    {
      logId: '13852277462472114778',
      concreteTypeId:
        'c03d2cf5a8ccc25a3bddb9f19daa56503610c857cc816fd4e0dc5c304252a5d3',
    },
    {
      logId: '4571204900286667806',
      concreteTypeId:
        '3f702ea3351c9c1ece2b84048006c8034a24cbc2bad2e740d0412b4172951d3d',
    },
    {
      logId: '7815807991795909563',
      concreteTypeId:
        '6c7753f567a783bb9490cf39a6c2adf9aeeae5b8d0fd6fab4fa60f44bbc38781',
    },
    {
      logId: '12970362301975156672',
      concreteTypeId:
        'b3fffbcb3158d7c010c31b194b60fb7857adb4ad61bdcf4b8b42958951d9f308',
    },
  ],
  messagesTypes: [],
  configurables: [],
};

const storageSlots: StorageSlot[] = [
  {
    key: '384ae36c40b1dc65eb8ce767e18dcf2acc74aed2058f589f252be9312ff4ef6e',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'cd5d45b2e55e3b83e49302a92fb80c775d8fe75087ea1a1d3a4dacf7f26b58ec',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'cd5d45b2e55e3b83e49302a92fb80c775d8fe75087ea1a1d3a4dacf7f26b58ed',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'e07696695ba9e19541fd31df38411d0f0d45dab31133c2d91b3c0d6f5f2970c6',
    value: '0000000000000000000000000000000000000000000000000000000000000000',
  },
  {
    key: 'e1a72c9f3f502d7ead2f1a413448e7c6e2bd9f94a1205054bb7d434986b5e2ed',
    value: '00000000000000030000000000000e1000000000000013880000000000000000',
  },
];

export class PricefeedInterface extends Interface {
  constructor() {
    super(abi);
  }

  declare functions: {
    end_round: FunctionFragment;
    get_config: FunctionFragment;
    get_price: FunctionFragment;
    get_round_data: FunctionFragment;
    initialize: FunctionFragment;
    is_price_submitter: FunctionFragment;
    latest_round: FunctionFragment;
    set_config: FunctionFragment;
    set_price_submitter: FunctionFragment;
    submit_price: FunctionFragment;
    total_active_submitters: FunctionFragment;
    transfer_ownership: FunctionFragment;
    owner: FunctionFragment;
  };
}

export class Pricefeed extends Contract {
  static readonly abi = abi;
  static readonly storageSlots = storageSlots;

  declare interface: PricefeedInterface;
  declare functions: {
    end_round: InvokeFunction<[round_id: BigNumberish], void>;
    get_config: InvokeFunction<[], ConfigOutput>;
    get_price: InvokeFunction<[], PriceOutput>;
    get_round_data: InvokeFunction<[round_id: BigNumberish], RoundOutput>;
    initialize: InvokeFunction<
      [
        owner: IdentityInput,
        config: ConfigInput,
        submitters: Vec<IdentityInput>,
      ],
      void
    >;
    is_price_submitter: InvokeFunction<[submitter: IdentityInput], boolean>;
    latest_round: InvokeFunction<[], RoundOutput>;
    set_config: InvokeFunction<[config: ConfigInput], void>;
    set_price_submitter: InvokeFunction<
      [submitter: IdentityInput, is_valid: boolean],
      void
    >;
    submit_price: InvokeFunction<
      [price: BigNumberish, round_id: BigNumberish],
      void
    >;
    total_active_submitters: InvokeFunction<[], BN>;
    transfer_ownership: InvokeFunction<[new_owner: IdentityInput], void>;
    owner: InvokeFunction<[], StateOutput>;
  };

  constructor(id: string | Address, accountOrProvider: Account | Provider) {
    super(id, abi, accountOrProvider);
  }
}
